### ISSUE TITLE
Missing plugins Pagination, Breadcrumbs, Taxonomy List

### ISSUE THREAD

**Issue by s6h9** [getgrav/grav-skeleton-blog-site#1]
On getgrav.org (http://getgrav.org/downloads/skeletons) the desciption of this skeleton is: "The Blog Skeleton provides you with sample blog content and plugins including: Pagination, Breadcrumbs, and Taxonomy List." - The plugins are missing, or couldn't I find them?

**Comment by rhukster** [comment]
you need to run `bin/grav install` after you have replaced your default `user` folder with the skeleton.  This will install the dependencies which are listed, but not included in the skeleton.
