### ISSUE TITLE
Admin Account / Password

### ISSUE THREAD

**Issue by ulab** [getgrav/grav-skeleton-blog-site#10]
Is there a reason why you include your admin.yaml file in this repository?

It seems like it is not delivered with the downloadable archive on the grav website, but if people use the repository as a base for some reason, they install credentials that a decent password tool cracks in less than 2 seconds.

**Comment by flaviocopes** [comment]
I believe this was committed by mistake, thanks for the ping

**Comment by flaviocopes** [comment]
Fixed in repo
