### ISSUE TITLE
Grid content rendering off-page on iPhone

### ISSUE THREAD

**Issue by goldjg** [getgrav/grav-skeleton-blog-site#12]
I have the skeleton repo cloned as basis for a site and everything looks good on a Windows 10 PC and on an iPad. 

On iPhone everything is fine in landscape mode but in portrait view the text is cut off at the left of the screen - you can see it live at https://whytesideaction.info.

Source is at https://github.com/goldjg/whytesideaction.

Pretty sure I didn’t change anything in the theme etc that would have caused it but there’s every chance...

**Comment by goldjg** [comment]
I’ve rebased the whole site except /user/pages and still get the same issues. Drop in the demo pages from skeleton and they render fine. Removed single quotes from my blog item headers, removed extraneous headers I’d inherited by copying blog.md as a template for my item.md pages and still no joy. I have a suspicion Windows newlines vs Linux newlines could be an issue even though this is running as an Azure web app on Windows. Definitely a content/markdown issue in my content but haven’t nailed it yet.

**Comment by goldjg** [comment]
Works in Portrait mode in Firefox browser on Android 7 (Lollipop)
Doesn’t work in Portrait mode on Chrome (iOS 11.4.1 and Android) or Safari (iOS 11.4.1)

**Comment by goldjg** [comment]
Ensured all were encoded as UTF-8 and use LF rather than CRLF for newlines. Still no joy. Had a look in css etc though that area is not my strong suit.

**Comment by goldjg** [comment]
I’ve finally found the issue - blog posts with urls in the markdown that didn’t have any square brackets and parentheses. As soon as they are in any post on a listing page, every card renders partially off-page.

**Comment by rhukster** [comment]
Is this an issue still? can it be closed?

**Comment by goldjg** [comment]
Maybe - depends if you think putting a url straight into the markdown of a blog post (e.g. https://www.google.com) instead of with proper markdown (e.g. \[click here\](https://www.google.com) should completely break rendering of a paginated collection?

Is it enough to say that if your markdown isn’t quite correct then strange things will happen (and close the issue) or should this case be handled somehow? I’m happy with either approach.

**Comment by goldjg** [comment]
I'm going to close this now but hopefully anyone else making the same mistake will find it and have their eureka moment!
