### ISSUE TITLE
What's about the pages\authors folder?

### ISSUE THREAD

**Issue by oscon** [getgrav/grav-skeleton-blog-site#4]
Sorry, but to what is the user\pages\authors folder needed?

**Comment by ghost** [comment]
Looks like it's not really connected to anything (yet). Should not be hard to wire it up. :)

I guess the idea is to have a authors link that opens a new authors page, or render author information into a sidebar block of some kind.

**Comment by rhukster** [comment]
Yah it was used at one point, but then got dropped but we never removed the folder.  I've removed it now.
