### ISSUE TITLE
Contact form modular

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-skeleton-blog-site#6]
Hi guys,

I've been trying to play with this for a little bit and I can seem to add a form page with  no problem following the docs.
However, the page should be modular so i could add other things like articles / sidebar items, etc...

I managed to copy the form\* from antimatter and got to the point where the site was displaying 2 nav bars. I managed to get rid of the extra nav bar but I still cannot see the form in frontend. 
Is there something small that  I am missing somehow ?

**Comment by flaviocopes** [comment]
Did you check http://learn.getgrav.org/forms/forms/how-to-forms-in-modular-pages?

**Comment by JohnMica** [comment]
Tried that but no luck so that's why i thought you could help out a bit. i posted on gitter maybe who knows what I'm missing
