### ISSUE TITLE
Archives KO on skeleton-blog-site

### ISSUE THREAD

**Issue by gcegithub** [getgrav/grav-skeleton-blog-site#7]
Hi,

deployed on : XAMPP Version: 5.6.21

**Use case: ARCHIVE**
- download getgrav.org/downloads/skeletons/Blog Site v1.1.1
- click on may or june.. archive
- return page : error 403

**Use case: Popular Tags**
- download getgrav.org/downloads/skeletons/Blog Site v1.1.1
- click on a tag
- return page : error 403

**Note**
the demo version http://demo.getgrav.org/blog-skeleton/  is working well with archive and tags.

regards,

**Comment by flaviocopes** [comment]
Are you using Windows? If so, set the `Parameter separator` setting to `;` in the System configuration.

**Comment by gcegithub** [comment]
Thanks a lot, you was true.
You teach me more about grav ;-)
