### ISSUE TITLE
Provide the Admin Panel with this skeleton by default?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav-skeleton-blog-site#8]
To help further spread the adoption of Grav, and streamline the first-use experience for more moderately tech-savvy users, I think it would be helpful to include the Admin Panel in this skeleton (and as well the Antimatter One-Page Site skeleton).

Thanks for considering this request,
Paul

**Comment by flaviocopes** [comment]
I think all skeletons should include Admin at some point, not sure what @rhukster thinks about this
